### ISSUE TITLE
RA3 Uprising doesn't work/

### ISSUE THREAD

**Issue by quake1982** [MetaIdea/SageMetaTool#12] opened 2024-03-16 12:26 UTC
I downloaded the v0.7 hotfix 2, it shows this:

![Screenshot 2024-03-17 012449](https://github.com/MetaIdea/SageMetaTool/assets/77327148/84fc59f0-582a-4f1c-9f3f-860ba114acd3)

**Comment by MetaIdea** [comment] 2024-03-16 12:40
OK this is weird. I just changed my game language to english to get the same conditions and it works. What happens if you run the tool as admin, any change ? Also can you check games file integrity with steam plus start the game at least once after that.

**Comment by quake1982** [comment] 2024-03-17 01:26
Thank you for replying.
As you mentioned, I assure you that the language is English.
![Screenshot 2024-03-17 115427](https://github.com/MetaIdea/SageMetaTool/assets/77327148/a04a5d36-89cc-4f16-be04-20a1f767482f)
Also, all files of installation are intact
![Screenshot 2024-03-17 115358](https://github.com/MetaIdea/SageMetaTool/assets/77327148/c11cabaf-3325-429d-a700-8a9494f21823)
Still, the issue exists.
Next move, trying to remove the registry and reinstall the game, see how it goes.

**Comment by MetaIdea** [comment] 2024-03-17 02:09
The issue is with the steam install being bugged that does not add the regular uprising registry keys at all. I'm working on a workaround to retrieve infos from "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 24800"

**Comment by quake1982** [comment] 2024-03-17 05:49
Thank you for the digging, I will wait for the next hotfix of the tool. If you have any suggestions, please let me know. Cheers!

**Comment by MetaIdea** [comment] 2024-03-18 00:44
It's fixed now. It uses a alternative method to detect.

**Closed** 2024-03-18 00:45 UTC
